# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ssherman-sysloglogger"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Erik Hodel", "Shane Sherman"]
  s.date = "2012-12-07"
  s.description = "wrapper around syslog that's rails friendly. Forked and added ability to set options"
  s.email = "shane.sherman@gmail.com"
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
    "Manifest.txt",
    "README.txt",
    "Rakefile",
    "VERSION",
    "lib/analyzer_tools/syslog_logger.rb",
    "lib/syslog/logger.rb",
    "lib/sysloglogger.rb",
    "test/test_syslog_logger.rb"
  ]
  s.homepage = "http://github.com/ssherman/sysloglogger"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "wrapper around syslog that's rails friendly"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

